### ISSUE TITLE
Use pathlib.Path for handling paths

### ISSUE THREAD

**Issue by jigarius** [jigarius/clibato#10]
## Requirements

Turns out that `pathlib.Path` can provide an excellent wrapper for filesystem paths. Using it will surely clean things up and remove imports of packages like `os`.

    path = pathlib.Path('~/.clibato.yml')
    path.is_absolute() # False
    path.absolute() # /var/www/.clibato.yml

It also provides methods like `is_file()`, `is_dir()`, etc.

## To-do

  - [x] Use `pathlib.Path` in `clibato.Config`
  - [x] Use `pathlib.Path` in `clibato.Content`
  - [x] Use `pathlib.Path` in `clibato.Destination`
  - [x] Replace misc `os.path.*`

**Comment by jigarius** [comment]
Woo! Python's `pathlib.Path` is mind-blowingly awesome.
